name: Custom Email Test Workflow

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 24f1001925@ds.study.iitm.ac.in
        run: echo "Hello, world!"
